app:
  upload:
    dir: C:\etutor_document_uploads

spring:
  application:
    name: ewsd-etutor-backend
  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 25MB

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ewsd_local
    username: root
    password: Htut2003@@@

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop # use 'validate' in production
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always

  security:
    filter:
      order: 5

# JWT Configuration
jwt:
  secret: a-string-secret-at-least-256-bits-long
  expiration: 3600000  # 1 hour in milliseconds
  refresh:
    expiration: 604800000  # 7 days in milliseconds

# Server Configuration
server:
  port: 8080
  error:
    include-message: always